package main

import (
	"new-alunos/servers"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "new-alunos/docs"
)

// @title Alunos Example
// @version 1.0
// @description This is a sample swagger for Fiber
// @termsOfService http://swagger.io/terms/
// @contact.name Eduardo Rossini
// @contact.email ajuda.apple@gmail.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:6000
// @BasePath /

func main() {
	go servers.GrpcStart()
	servers.HttpStart()
}
