// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: protoimp/alunos.proto

package alunos_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchAlunoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *GetAlunosParams `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *SearchAlunoRequest) Reset() {
	*x = SearchAlunoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAlunoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlunoRequest) ProtoMessage() {}

func (x *SearchAlunoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlunoRequest.ProtoReflect.Descriptor instead.
func (*SearchAlunoRequest) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{0}
}

func (x *SearchAlunoRequest) GetFilter() *GetAlunosParams {
	if x != nil {
		return x.Filter
	}
	return nil
}

type SearchAlunoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aluno *Aluno `protobuf:"bytes,1,opt,name=aluno,proto3" json:"aluno,omitempty"`
}

func (x *SearchAlunoResponse) Reset() {
	*x = SearchAlunoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAlunoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAlunoResponse) ProtoMessage() {}

func (x *SearchAlunoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAlunoResponse.ProtoReflect.Descriptor instead.
func (*SearchAlunoResponse) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{1}
}

func (x *SearchAlunoResponse) GetAluno() *Aluno {
	if x != nil {
		return x.Aluno
	}
	return nil
}

type NewAluno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Serie          string `protobuf:"bytes,2,opt,name=serie,proto3" json:"serie,omitempty"`
	Cpf            string `protobuf:"bytes,3,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Email          string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Datanascimento string `protobuf:"bytes,5,opt,name=datanascimento,proto3" json:"datanascimento,omitempty"`
	Cep            string `protobuf:"bytes,6,opt,name=cep,proto3" json:"cep,omitempty"`
	Coin           string `protobuf:"bytes,7,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (x *NewAluno) Reset() {
	*x = NewAluno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAluno) ProtoMessage() {}

func (x *NewAluno) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAluno.ProtoReflect.Descriptor instead.
func (*NewAluno) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{2}
}

func (x *NewAluno) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewAluno) GetSerie() string {
	if x != nil {
		return x.Serie
	}
	return ""
}

func (x *NewAluno) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *NewAluno) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewAluno) GetDatanascimento() string {
	if x != nil {
		return x.Datanascimento
	}
	return ""
}

func (x *NewAluno) GetCep() string {
	if x != nil {
		return x.Cep
	}
	return ""
}

func (x *NewAluno) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

type Aluno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Serie          string           `protobuf:"bytes,3,opt,name=serie,proto3" json:"serie,omitempty"`
	Cpf            string           `protobuf:"bytes,4,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Email          string           `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Datanascimento string           `protobuf:"bytes,6,opt,name=datanascimento,proto3" json:"datanascimento,omitempty"`
	Idade          int32            `protobuf:"varint,7,opt,name=idade,proto3" json:"idade,omitempty"`
	Endereco       *Address         `protobuf:"bytes,8,opt,name=endereco,proto3" json:"endereco,omitempty"`
	CoinName       string           `protobuf:"bytes,9,opt,name=CoinName,proto3" json:"CoinName,omitempty"`
	CoinResponse   *GetCoinResponse `protobuf:"bytes,10,opt,name=CoinResponse,proto3" json:"CoinResponse,omitempty"`
}

func (x *Aluno) Reset() {
	*x = Aluno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aluno) ProtoMessage() {}

func (x *Aluno) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aluno.ProtoReflect.Descriptor instead.
func (*Aluno) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{3}
}

func (x *Aluno) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Aluno) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Aluno) GetSerie() string {
	if x != nil {
		return x.Serie
	}
	return ""
}

func (x *Aluno) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *Aluno) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Aluno) GetDatanascimento() string {
	if x != nil {
		return x.Datanascimento
	}
	return ""
}

func (x *Aluno) GetIdade() int32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

func (x *Aluno) GetEndereco() *Address {
	if x != nil {
		return x.Endereco
	}
	return nil
}

func (x *Aluno) GetCoinName() string {
	if x != nil {
		return x.CoinName
	}
	return ""
}

func (x *Aluno) GetCoinResponse() *GetCoinResponse {
	if x != nil {
		return x.CoinResponse
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cep         string `protobuf:"bytes,1,opt,name=cep,proto3" json:"cep,omitempty"`
	Logradouro  string `protobuf:"bytes,2,opt,name=logradouro,proto3" json:"logradouro,omitempty"`
	Bairro      string `protobuf:"bytes,3,opt,name=bairro,proto3" json:"bairro,omitempty"`
	Localidade  string `protobuf:"bytes,4,opt,name=localidade,proto3" json:"localidade,omitempty"`
	Uf          string `protobuf:"bytes,5,opt,name=uf,proto3" json:"uf,omitempty"`
	Complemento string `protobuf:"bytes,6,opt,name=complemento,proto3" json:"complemento,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{4}
}

func (x *Address) GetCep() string {
	if x != nil {
		return x.Cep
	}
	return ""
}

func (x *Address) GetLogradouro() string {
	if x != nil {
		return x.Logradouro
	}
	return ""
}

func (x *Address) GetBairro() string {
	if x != nil {
		return x.Bairro
	}
	return ""
}

func (x *Address) GetLocalidade() string {
	if x != nil {
		return x.Localidade
	}
	return ""
}

func (x *Address) GetUf() string {
	if x != nil {
		return x.Uf
	}
	return ""
}

func (x *Address) GetComplemento() string {
	if x != nil {
		return x.Complemento
	}
	return ""
}

type AlunosList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alunos []*Aluno `protobuf:"bytes,1,rep,name=alunos,proto3" json:"alunos,omitempty"`
}

func (x *AlunosList) Reset() {
	*x = AlunosList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlunosList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlunosList) ProtoMessage() {}

func (x *AlunosList) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlunosList.ProtoReflect.Descriptor instead.
func (*AlunosList) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{5}
}

func (x *AlunosList) GetAlunos() []*Aluno {
	if x != nil {
		return x.Alunos
	}
	return nil
}

type GetAlunosParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpf  string `protobuf:"bytes,1,opt,name=cpf,proto3" json:"cpf,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAlunosParams) Reset() {
	*x = GetAlunosParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAlunosParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlunosParams) ProtoMessage() {}

func (x *GetAlunosParams) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlunosParams.ProtoReflect.Descriptor instead.
func (*GetAlunosParams) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlunosParams) GetCpf() string {
	if x != nil {
		return x.Cpf
	}
	return ""
}

func (x *GetAlunosParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name é o nome da moeda, serve tanto para o símbolo(BTC, ETH) ou nome completo(Bitcoin)
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetCoinRequest) Reset() {
	*x = GetCoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinRequest) ProtoMessage() {}

func (x *GetCoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinRequest.ProtoReflect.Descriptor instead.
func (*GetCoinRequest) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{7}
}

func (x *GetCoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name é o nome da moeda em letras minúsculas ex.: bitcoin
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Price é o valor corrente da crypto em "Currency"
	Price float64 `protobuf:"fixed64,2,opt,name=Price,proto3" json:"Price,omitempty"`
	// Symbol é a moeda a ser utilizada ex.: USD
	Currency string `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
}

func (x *GetCoinResponse) Reset() {
	*x = GetCoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoimp_alunos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinResponse) ProtoMessage() {}

func (x *GetCoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoimp_alunos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinResponse.ProtoReflect.Descriptor instead.
func (*GetCoinResponse) Descriptor() ([]byte, []int) {
	return file_protoimp_alunos_proto_rawDescGZIP(), []int{8}
}

func (x *GetCoinResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCoinResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetCoinResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_protoimp_alunos_proto protoreflect.FileDescriptor

var file_protoimp_alunos_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2f, 0x61, 0x6c, 0x75, 0x6e, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d,
	0x70, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x75, 0x6e, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x13, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x05, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x41, 0x6c, 0x75, 0x6e,
	0x6f, 0x52, 0x05, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x08, 0x4e, 0x65, 0x77,
	0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x72,
	0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x70, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70,
	0x66, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e,
	0x61, 0x73, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x61, 0x73, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x65, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x65,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x69, 0x6e, 0x22, 0xb1, 0x02, 0x0a, 0x05, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x65, 0x72, 0x69, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x66,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x61, 0x73, 0x63, 0x69, 0x6d, 0x65,
	0x6e, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x6e,
	0x61, 0x73, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x61,
	0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x64, 0x61, 0x64, 0x65, 0x12,
	0x2d, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x43, 0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x43, 0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x43, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x65, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x72, 0x61,
	0x64, 0x6f, 0x75, 0x72, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x67,
	0x72, 0x61, 0x64, 0x6f, 0x75, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x69, 0x72, 0x72,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x69, 0x72, 0x72, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x64, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x75, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x75, 0x66, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x6f, 0x22, 0x35, 0x0a, 0x0a, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x06, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x41, 0x6c, 0x75, 0x6e, 0x6f,
	0x52, 0x06, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x70, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x66, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x32, 0xc7, 0x03, 0x0a, 0x0f, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x4d, 0x61, 0x6e, 0x65, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6c,
	0x75, 0x6e, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x4e,
	0x65, 0x77, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x70, 0x2e, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x41, 0x6c,
	0x75, 0x6e, 0x6f, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x41, 0x6c, 0x75,
	0x6e, 0x6f, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6c,
	0x75, 0x6e, 0x6f, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x4e,
	0x65, 0x77, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x70, 0x2e, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e,
	0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x69, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x69, 0x6d, 0x70, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x75, 0x6e, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69,
	0x6d, 0x70, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x79,
	0x62, 0x6f, 0x72, 0x67, 0x72, 0x6a, 0x2f, 0x6e, 0x65, 0x77, 0x2d, 0x61, 0x6c, 0x75, 0x6e, 0x6f,
	0x73, 0x3b, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoimp_alunos_proto_rawDescOnce sync.Once
	file_protoimp_alunos_proto_rawDescData = file_protoimp_alunos_proto_rawDesc
)

func file_protoimp_alunos_proto_rawDescGZIP() []byte {
	file_protoimp_alunos_proto_rawDescOnce.Do(func() {
		file_protoimp_alunos_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoimp_alunos_proto_rawDescData)
	})
	return file_protoimp_alunos_proto_rawDescData
}

var file_protoimp_alunos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protoimp_alunos_proto_goTypes = []interface{}{
	(*SearchAlunoRequest)(nil),  // 0: protoimp.SearchAlunoRequest
	(*SearchAlunoResponse)(nil), // 1: protoimp.SearchAlunoResponse
	(*NewAluno)(nil),            // 2: protoimp.NewAluno
	(*Aluno)(nil),               // 3: protoimp.Aluno
	(*Address)(nil),             // 4: protoimp.Address
	(*AlunosList)(nil),          // 5: protoimp.AlunosList
	(*GetAlunosParams)(nil),     // 6: protoimp.GetAlunosParams
	(*GetCoinRequest)(nil),      // 7: protoimp.GetCoinRequest
	(*GetCoinResponse)(nil),     // 8: protoimp.GetCoinResponse
}
var file_protoimp_alunos_proto_depIdxs = []int32{
	6,  // 0: protoimp.SearchAlunoRequest.filter:type_name -> protoimp.GetAlunosParams
	3,  // 1: protoimp.SearchAlunoResponse.aluno:type_name -> protoimp.Aluno
	4,  // 2: protoimp.Aluno.endereco:type_name -> protoimp.Address
	8,  // 3: protoimp.Aluno.CoinResponse:type_name -> protoimp.GetCoinResponse
	3,  // 4: protoimp.AlunosList.alunos:type_name -> protoimp.Aluno
	2,  // 5: protoimp.AlunoManegement.CreateAluno:input_type -> protoimp.NewAluno
	6,  // 6: protoimp.AlunoManegement.GetAlunos:input_type -> protoimp.GetAlunosParams
	6,  // 7: protoimp.AlunoManegement.GetAluno:input_type -> protoimp.GetAlunosParams
	2,  // 8: protoimp.AlunoManegement.UpdateAluno:input_type -> protoimp.NewAluno
	6,  // 9: protoimp.AlunoManegement.DeleteAluno:input_type -> protoimp.GetAlunosParams
	7,  // 10: protoimp.AlunoManegement.GetCoin:input_type -> protoimp.GetCoinRequest
	0,  // 11: protoimp.AlunoManegement.SearchAlunos:input_type -> protoimp.SearchAlunoRequest
	3,  // 12: protoimp.AlunoManegement.CreateAluno:output_type -> protoimp.Aluno
	5,  // 13: protoimp.AlunoManegement.GetAlunos:output_type -> protoimp.AlunosList
	3,  // 14: protoimp.AlunoManegement.GetAluno:output_type -> protoimp.Aluno
	3,  // 15: protoimp.AlunoManegement.UpdateAluno:output_type -> protoimp.Aluno
	3,  // 16: protoimp.AlunoManegement.DeleteAluno:output_type -> protoimp.Aluno
	8,  // 17: protoimp.AlunoManegement.GetCoin:output_type -> protoimp.GetCoinResponse
	1,  // 18: protoimp.AlunoManegement.SearchAlunos:output_type -> protoimp.SearchAlunoResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protoimp_alunos_proto_init() }
func file_protoimp_alunos_proto_init() {
	if File_protoimp_alunos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoimp_alunos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAlunoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAlunoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAluno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aluno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlunosList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAlunosParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoimp_alunos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoimp_alunos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoimp_alunos_proto_goTypes,
		DependencyIndexes: file_protoimp_alunos_proto_depIdxs,
		MessageInfos:      file_protoimp_alunos_proto_msgTypes,
	}.Build()
	File_protoimp_alunos_proto = out.File
	file_protoimp_alunos_proto_rawDesc = nil
	file_protoimp_alunos_proto_goTypes = nil
	file_protoimp_alunos_proto_depIdxs = nil
}
